In [1]:
%load_ext autoreload
%autoreload 1

%aimport plot_helpers
%aimport file_helpers
%aimport integration

In [2]:
from file_helpers import *
from plot_helpers import *
from integration import *
%matplotlib inline

In [3]:
get_dir('data/manual')

In [4]:
validation = pd.read_csv

15-07-17 DSC Prep #29-33 validation.xlsx        15-08-12 DSC Prep 29-52 validation.xlsx
15-07-22 DSC Prep #34-40 & POS validation.xlsx  ~$15-08-12 DSC Prep 29-52 validation.xlsx

In [18]:
all_preps = pd.read_excel('15-08-12 DSC Prep 29-52 validation.xlsx', skiprows = 2)
names = list(all_preps.columns)
names[8] = 'enthalpy'
all_preps.columns = names

In [22]:
all_preps[['Isolate ID', 'enthalpy']]

    Isolate ID                                           enthalpy
0           29                                              2.781
1           29                                              2.571
2           30                                              2.803
3           30                                              2.285
4           31                                               2.09
5           31                                                NaN
6           42  1.443 (cannot figure out how to change mg to c...
7           42                                              4.962
8           33                                              2.236
9           33                                              2.288
10          34                                              2.718
11          34                                              2.685
12          36                                              3.436
13          36                                              3.231
14          37                                              2.748
15          37                                              2.713
16          39                                                3.9
17          39                                              3.535
18          40                                                NaN
19          40                                                NaN
20          41                                              3.018
21          41                                              3.063
22          43                                              3.177
23          43                                              3.486
24          44                                              3.875
25          44                                              4.624
26          45                                              3.929
27          45                                              2.059
28          40                                              6.408
29          40                                                NaN
30          46                                              3.841
31          46                                              2.782
32          47                                              3.728
33          47                                              3.294
34          48                                              3.611
35          48                                               3.15
36          49                                              3.322
37          49                                               3.13
38          50                                              3.498
39          50                                              3.169
40          51                                              3.352
41          51                                              3.583
42          52                                              3.889
43          52                                              3.051

In [23]:
e = all_preps.enthalpy

In [25]:
map(float, e)

ValueError: invalid literal for float(): 1.443 (cannot figure out how to change mg to correct amount (also mislabeled as 31)